marmelab/ng-admin

src/javascripts/ng-admin/Crud/repository/RetrieveQueries.js
Moved identifiers retrieval before calling `getSingleApiCall` on `getReferencedValues` method.
Screenshot demonstrating the problem:
=> retrieve identifiers before getSingleApiCall call

src/javascripts/ng-admin/Crud/column/maReferencedListColumn.js, src/javascripts/ng-admin/Crud/list/Datagrid.html, src/javascripts/ng-admin/Crud/list/DatagridController.js, src/javascripts/ng-admin/Crud/list/DatagridPagination.html, src/javascripts/ng-admin/Crud/list/list.html, src/javascripts/ng-admin/Crud/list/maDatagrid.js, src/javascripts/ng-admin/Crud/list/maDatagridPagination.js, src/javascripts/test/unit/Crud/list/maDatagridSpec.js, src/sass/ng-admin.scss
We can simplify the datagrid code (and binding) by moving the pagination out.
Also, using one-way databinding for entries to save on memory.
Finally, the pagination markup can be simplified to use native bootstrap components.
=> [RFR] Don't transit pagination through datagrid

README.md
* The `limit` field of the `dashboardView` is used in the example, but not listed in the documentation.
* Also it is not mentioned, that you can use `sortField` and `sortDir` fields on a `dashboardView` (Both are not part of the general view settings and the `dashboardView` is only described as an "another special view", so it's not clear that this fields form the `listView` can be used for an `dashboardView` too).
=> Update readme: dashboardView section

README.md, doc/Theming.md, src/javascripts/ng-admin/Crud/column/maColumn.js, src/javascripts/ng-admin/Main/component/service/config/Field.js
By default the `isDetailLink` field is linked to the edition view (or to the show view, if it is linked to a read only entity). I think there a cases, where you don't want to jump form the list view to the edition view of a specific item. That's why I added the following:
`detailLinkRoute(string)`
Define the route for a link in the list view, i.e. `isDetailLink` is true. The default is `edit`, hence the link points to the edition view. The other option is `show` to point to the show view.
Let me know, if I should change or improve something.
=> Add option to define the route on a `isDetailLink` field

src/javascripts/ng-admin/Crud/routing.js
Fix the sorting of ReferencedList fields in the showView. #254 (commit bc7745e54b6a1308d3b753fd6a65364bcbc1cc3f) wasn't enough to really fix it. Now it's possible to sort the ReferencedList table by a column.
=> Fix the sorting of ReferencedList fields in the showView.

src/javascripts/ng-admin/Crud/form/edit-attribute.html
Non-editable choices field, for instance, need to be displayed as label, not value. Same for date field, etc. So instead of displaying the raw value, the creation and edition form fallback to a column.
=> [RFR] Fallback to column for non-editable fields in form

src/javascripts/ng-admin/Crud/column/maColumn.js
Fixes:
```js
new Reference('fuel_type_id')
.label('Fuel type')
.targetEntity(fuel_type)
.isDetailLink(false)
.targetField(new Field('name')) // didn't work
```
refs #144
=> [RFR] Allow isEditLink to disable links on references

src/javascripts/ng-admin/Crud/column/maColumn.js, src/javascripts/ng-admin/Main/component/service/config/ReferencedList.js
=> [RFR] Allow listActions on ReferencedList

src/javascripts/ng-admin/Crud/field/maFileField.js
Because a input type file cannot be required on edit as It does not have any value.
We cannot distinguish when upload is really finish with progress bar, so, when the progress disappear, we can really know that upload is finished.
=> [RFR] Remove file field requirement on edition and remove file upload progress bar on end

README.md, src/javascripts/ng-admin/Crud/delete/delete.html, src/javascripts/ng-admin/Crud/form/create.html, src/javascripts/ng-admin/Crud/form/edit.html, src/javascripts/ng-admin/Crud/list/list.html, src/javascripts/ng-admin/Crud/show/show.html
Compile the `description` like the `title`. That means you can customize both with details from the current entry.
For instance you could display the ID of an entry in the `title` and the name in the `description`, because the names are too long for a big heading. Or you want to display some other extra information about the entry in the description.
=> Compile description field

README.md, UPGRADE-0.6.md, doc/API-mapping.md, doc/Custom-pages.md, doc/Theming.md, examples/blog/config.js, src/javascripts/ng-admin/Main/component/provider/NgAdminConfiguration.js
Implements the first part of the changes proposed in #294. This PR is backwards compatible, meaning that using `new Field()` is still supported at this point.
I suggest we merge this one quickly to let users write configuration with factories as of now. Additional features (subclassing Field, overriding default fields) won't harm users who already use the factory syntax.
=> [RFR] Introducing Factory methods

README.md, src/javascripts/ng-admin/Crud/repository/RetrieveQueries.js, src/javascripts/ng-admin/Main/component/service/config/Reference.js
We can now apply filters on reference fields:
```js
nga.field('post_id', 'reference')
.targetEntity(nga.entity('post'))
.targetField(nga.field('title', 'string')))
.filters({ 'is_published': true })
```
=> [RFR] Add possibility to filter references results

Gruntfile.js
Icons from FontAwesome webfont is unavailable when running "make run" in newly clonned repo (with "make install" executed, of course). The reason of such behaviour is the absence of *assets/fonts/* folder in the example root folder */example/blog/*.
So I added "copy:assets_dev" grunt task, which copies assets folder to the example root, and included this task to the "watch:sass" task settings, where it should be IMO.
=> fix: 404 error for fontawesome-webfont on local example server

examples/blog/config.js
We used to send a simple string to the backend, now we send a serialized date. Unfortunately, the backend used in the blog example doesn't understand dates, and even less timezones. So we do the job in the frontend of undoing timezone offset and sending the raw date.
Closes #345
=> [RFR] Fix date sent to json_server in blog example

README.md, examples/blog/config.js, src/javascripts/ng-admin/Crud/config/factories.js, src/javascripts/ng-admin/Main/component/service/config/fieldTypes/DateField.js, src/javascripts/ng-admin/Main/component/service/config/fieldTypes/DateTimeField.js, src/javascripts/ng-admin/Main/config/factories.js
Uses a simple datepicker widget (similar to date field), but allows to
enter time.
Supersedes #297
Also, fixes the date field to skip timezones entirely (refs #345, #347)
=> [RFR] Introducing datetime field

README.md, examples/blog/config.js, src/javascripts/ng-admin/Crud/CrudModule.js, src/javascripts/ng-admin/Crud/button/maFilteredListButton.js, src/javascripts/ng-admin/Crud/button/maListButton.js, src/javascripts/ng-admin/Crud/form/FormController.js
A reusable directive to automatically link to a prefiltered list.
Usage: 
```js
post.editionView()
.fields([
nga.field('comments', 'referenced_list')
.targetEntity(comment)
.targetReferenceField('post_id')
.targetFields([
nga.field('id'),
nga.field('body').label('Comment')
]),
nga.field('', 'template').label('')
.template('<ma-filtered-list-button entity-name="comments" filter="{ post_id: entry.values.id }" size="sm">')
```
Refs #338
=> [RFR] Add <ma-filtered-list-button> directive

README.md, src/javascripts/ng-admin/Crud/CrudModule.js, src/javascripts/ng-admin/Crud/column/maNumberColumn.js, src/javascripts/ng-admin/Crud/fieldView/NumberFieldView.js, src/javascripts/ng-admin/Main/component/service/config/fieldTypes/NumberField.js, src/javascripts/ng-admin/Main/config/factories.js
Specializing the 'number' type to allow to set the fractionSize:
```js
nga.field('height', 'number').fractionSize(2);
```
The value 123.45 will render as:
* 123.45 by default
* 123 when `fractionSize` is 0
* 123.4 when `fractionSize` is 1
* 123.45 when `fractionSize` is 2
* 123.456 when `fractionSize` is 3
* etc.
=> [RFR] Number field can now set fractionSize

.travis.yml
A test fails locally while Travis is green. This is due to a DateField issue with timezone.
=> [WIP] Change Travis timezone

README.md, src/javascripts/ng-admin/Crud/field/maFileField.js
If the uploaded file is renamed server-side, we can recover the new filename from an api return.
=> [RFR] add an option on maFileField to recover the serverside filename

src/javascripts/ng-admin/Crud/fieldView/ReferenceFieldView.js, src/javascripts/ng-admin/Crud/routing.js
When applying *.editable(false)* field method on field of "reference" type for EditView - we get no visible representation of this field - we get a link with empty inner text. This is because of getReadWidget() which passes an empty value to corresponding directive.
So I've slightly changed this function to fix this issue.
=> Fix: .editable(false) on "reference" type field in EditView

src/javascripts/ng-admin/Crud/form/FormController.js, src/javascripts/ng-admin/Crud/repository/UpdateQueries.js
It was a lot easier than I thought.
Fixed https://github.com/marmelab/ng-admin/issues/332
Checked and tested on example configuration.
But all changes to example configuration has been undone.
I've left only patch changes. Is that OK?
=> fix: Edit identity (primary key) field (#332 issue on GitHub)

README.md, bower.json, examples/blog/config.js, src/javascripts/ng-admin.js, src/javascripts/ng-admin/Crud/CrudModule.js, src/javascripts/ng-admin/Crud/button/maExportToCsvButton.js, src/javascripts/ng-admin/Crud/list/list.html, src/javascripts/ng-admin/Crud/misc/EntryFormater.js, src/javascripts/ng-admin/Crud/misc/view-actions.html, src/javascripts/ng-admin/Crud/repository/RetrieveQueries.js, src/javascripts/ng-admin/es6/lib/View/ListView.js
=> [WIP] integrate export-to-csv directive into ng-admin

README.md, UPGRADE-0.7.md, examples/blog/config.js, src/javascripts/ng-admin/Crud/delete/BatchDeleteController.js, src/javascripts/ng-admin/Crud/fieldView/ReferencedListFieldView.js, src/javascripts/ng-admin/Crud/form/FormController.js, src/javascripts/ng-admin/Crud/list/ListController.js, src/javascripts/ng-admin/Crud/repository/RetrieveQueries.js, src/javascripts/ng-admin/Crud/show/ShowController.js, src/javascripts/ng-admin/Main/component/service/Validator.js, src/javascripts/ng-admin/es6/lib/Entry.js, src/javascripts/ng-admin/es6/lib/Field/Field.js, src/javascripts/ng-admin/es6/lib/View/View.js, src/javascripts/ng-admin/es6/tests/lib/Field/ReferenceFieldTest.js, src/javascripts/ng-admin/es6/tests/lib/View/ViewTest.js, src/javascripts/test/unit/Main/component/service/PanelBuilderSpec.js, src/javascripts/test/unit/Main/component/service/config/view/ListViewSpec.js
=> [RFR] Refactor View.fields

src/javascripts/ng-admin/es6/lib/Application.js
The admin lost its default title when we moved the config to ES6. Bringing it back.
=> [RFR] Add default admin title

examples/blog/config.js, src/javascripts/ng-admin/Crud/button/maExportToCsvButton.js, src/javascripts/ng-admin/es6/lib/View/ExportView.js, src/javascripts/ng-admin/es6/lib/View/ListView.js
Was mistakenly removed by #386
=> [RFR] Re-add listView.exportFields() to configure export button

examples/blog/config.js, src/javascripts/ng-admin/Crud/column/maColumn.js, src/javascripts/ng-admin/Crud/delete/batchDelete.html, src/javascripts/ng-admin/Crud/delete/delete.html, src/javascripts/ng-admin/Crud/form/FormController.js, src/javascripts/ng-admin/Crud/form/create.html, src/javascripts/ng-admin/Crud/form/edit.html, src/javascripts/ng-admin/Crud/list/DatagridController.js, src/javascripts/ng-admin/Crud/list/ListActions.html, src/javascripts/ng-admin/Crud/list/list.html, src/javascripts/ng-admin/Crud/show/show.html, src/javascripts/ng-admin/Main/run/ErrorHandler.js, src/javascripts/ng-admin/Main/run/Loader.js
=> [RFR] Improve Disabled View Handling

src/javascripts/ng-admin/Crud/list/Datagrid.html
When displaying an array in a datagrid, ng-admin uses the array indexes as `$$hashKey`.
Because of that, if you do a `splice` on your array to remove an entry, it could lead to rendering issues.
=> [RFR] Fix rendering on datagrid by using entry.identifierValue as $$hashKey

README.md, src/javascripts/ng-admin/Crud/button/maBackButton.js, src/javascripts/ng-admin/Crud/button/maBatchDeleteButton.js, src/javascripts/ng-admin/Crud/button/maCreateButton.js, src/javascripts/ng-admin/Crud/button/maDeleteButton.js, src/javascripts/ng-admin/Crud/button/maEditButton.js, src/javascripts/ng-admin/Crud/button/maExportToCsvButton.js, src/javascripts/ng-admin/Crud/button/maFilteredListButton.js, src/javascripts/ng-admin/Crud/button/maListButton.js, src/javascripts/ng-admin/Crud/button/maShowButton.js
`maFilteredListButtonDirective` already had a `text` attribute for that. I've renamed it to `label` for more consistency.
=> [RFR] Add label attribute on button directives

src/sass/ng-admin.scss
Before:
After:
I can't add the unselected option to the list of choices because Angular throws me an infinite digest loop error (since I have to manipulate the return from `getChoices()` and it's always a new string litteral).
Closes #382
=> [RFR] Hide empty option in choice field

src/javascripts/ng-admin/es6/lib/Application.js, src/javascripts/ng-admin/es6/tests/lib/ApplicationTest.js
`baseApiUrl('/social/')` used to add the `/social/` prefix twice. Only absolute URLs (starting with `http://`) were added once.
Closes #405
=> [RFR] Fix relative baseApiUrl gets doubled in the URL

Gruntfile.js, README.md, examples/blog/config.js, examples/blog/index.html, src/javascripts/ng-admin.js, src/javascripts/ng-admin/Main/component/provider/NgAdminConfiguration.js, src/javascripts/ng-admin/es6/lib/Application.js, src/javascripts/test/protractor.conf.js
=> [RFR] Boost Angular app performance

src/javascripts/ng-admin/Crud/list/Datagrid.html, src/javascripts/ng-admin/Crud/list/DatagridController.js
=> [RFR] Fix empty list actions column

src/javascripts/ng-admin/Crud/routing.js, src/javascripts/ng-admin/es6/lib/Queries/ReadQueries.js, src/javascripts/ng-admin/es6/lib/Utils/PromisesResolver.js, src/javascripts/ng-admin/es6/lib/View/View.js, src/javascripts/ng-admin/es6/tests/lib/Queries/ReadQueriesTest.js
=> [RFR] Refactor referenced data

src/javascripts/ng-admin/Crud/column/maColumn.js, src/javascripts/ng-admin/Crud/delete/batchDelete.html, src/javascripts/ng-admin/Crud/delete/delete.html, src/javascripts/ng-admin/Crud/form/create.html, src/javascripts/ng-admin/Crud/form/edit.html, src/javascripts/ng-admin/Crud/routing.js, src/javascripts/ng-admin/Crud/show/show.html, src/javascripts/ng-admin/es6/lib/Application.js, src/javascripts/ng-admin/es6/lib/View/DeleteView.js, src/javascripts/ng-admin/es6/lib/View/MenuView.js, src/javascripts/ng-admin/es6/lib/View/View.js, src/javascripts/ng-admin/es6/tests/lib/ApplicationTest.js, src/javascripts/ng-admin/es6/tests/lib/Entity/EntityTest.js, src/javascripts/test/unit/Main/component/service/config/ApplicationSpec.js
=> [RFR] Fix button display when a view is disabled

src/javascripts/ng-admin/Crud/button/maBatchDeleteButton.js, src/javascripts/ng-admin/Crud/button/maCreateButton.js, src/javascripts/ng-admin/Crud/button/maDeleteButton.js, src/javascripts/ng-admin/Crud/button/maEditButton.js, src/javascripts/ng-admin/Crud/button/maListButton.js, src/javascripts/ng-admin/Crud/button/maShowButton.js, src/javascripts/ng-admin/Crud/delete/BatchDeleteController.js, src/javascripts/ng-admin/Crud/delete/DeleteController.js, src/javascripts/ng-admin/Crud/form/FormController.js, src/javascripts/ng-admin/Crud/routing.js, src/javascripts/test/e2e/ListViewSpec.js
save filter page and sort in state when going from list to edit/create/delete/batchdelete page, and restore it when going back to the list view.
=> [RFR]remember list filter when navigating on same entity. 

src/javascripts/ng-admin/Crud/button/maExportToCsvButton.js, src/javascripts/ng-admin/Crud/delete/DeleteController.js, src/javascripts/ng-admin/Crud/list/list.html, src/javascripts/ng-admin/Crud/misc/RestWrapper.js, src/javascripts/ng-admin/Crud/misc/ViewActions.js, src/javascripts/ng-admin/Crud/routing.js, webpack.config.js
Fix #458, #454, #455, #458 and #459.
Bonus: fix issue when using 'ng-strict-di' mode.
=> [RFR] Fix several bugs

src/javascripts/ng-admin/Crud/button/maExportToCsvButton.js
The issue was that promises wasn't resolved in the last step of the promises chain.
Fixed by removing `return rawEntries` at each step to return promises instead.
=> [RFR] Fix export CSV in firefox

package.json
I suggest to stay on AngularJS 1.3 as 1.4 breaks many things in ng-admin core and project using it (custom directive for example).
Because ng-admin embed by default the AngularJS dependency, all projects will be updated to the 1.4 version, and this will probably broke something.
=> [RFR] Stay on Angularjs 1.3 version

Makefile
Add better uglification, optimize Webpack internal ids and remove eventually duplicated code.
Before:
``` sh
$ ls -lh build/
total 2,8M
-rw-r--r-- 1 jpetitcolas jpetitcolas 1,4M May 29 10:01 ng-admin.min.css
-rw-r--r-- 1 jpetitcolas jpetitcolas 814K May 29 10:01 ng-admin.min.js
-rw-r--r-- 1 jpetitcolas jpetitcolas 7,0K May 29 10:01 ng-admin-only.min.css
-rw-r--r-- 1 jpetitcolas jpetitcolas 593K May 29 10:01 ng-admin-only.min.js
```
After:
``` sh
$ ls -lh build/
total 2,7M
-rw-r--r-- 1 jpetitcolas jpetitcolas 1,4M May 29 10:02 ng-admin.min.css
-rw-r--r-- 1 jpetitcolas jpetitcolas 796K May 29 10:02 ng-admin.min.js
-rw-r--r-- 1 jpetitcolas jpetitcolas 7,0K May 29 10:02 ng-admin-only.min.css
-rw-r--r-- 1 jpetitcolas jpetitcolas 575K May 29 10:02 ng-admin-only.min.js
```
=> [RFR] Optimize build process

src/javascripts/ng-admin/Crud/routing.js
Due to a missing DataStore usage.
Before:
After:
=> [RFR] Fix delete title

src/javascripts/ng-admin/Crud/delete/DeleteController.js, src/javascripts/ng-admin/Main/component/controller/DashboardController.js, src/javascripts/ng-admin/Main/component/service/PanelBuilder.js, src/javascripts/ng-admin/Main/view/dashboard.html, src/sass/ng-admin.scss
=> [RFR] Improve first contact: add invite after setup

src/javascripts/ng-admin/Crud/field/maInputField.js, src/javascripts/test/unit/Crud/field/maInputFieldSpec.js
Adding `float` type introduced a backward compatibility issue. As new `ma-input` directive now has a `ng-attr-step` attribute, it skipped the `step` attribute set through the `Field.attributes()` method.
This PR fixes it, allowing the following code:
``` js
nga.filter('count', 'number').attributes({ step: 'any' }).format('0.000');
```
To be equivalent to:
``` js
nga.filter('count', 'float');
```
=> [RFR] Fix BC issue with step attribute

src/javascripts/ng-admin/Crud/delete/BatchDeleteController.js, src/javascripts/test/e2e/ListViewSpec.js
need https://github.com/marmelab/admin-config/pull/12 to fix test.
=> [RFR] fix back method on batchDeleteController

Gruntfile.js, README.md, package.json, src/javascripts/ng-admin.js, src/javascripts/ng-admin/Crud/CrudModule.js, src/javascripts/ng-admin/Crud/field/maChoiceField.js, src/javascripts/ng-admin/Crud/field/maChoicesField.js, src/javascripts/ng-admin/Crud/field/uiSelectRequired.js, src/javascripts/ng-admin/Crud/fieldView/ChoiceFieldView.js, src/javascripts/ng-admin/Crud/filter/maFilter.js, src/javascripts/ng-admin/Crud/filter/maFilterController.js, src/javascripts/test/e2e/EditionViewSpec.js, src/javascripts/test/e2e/filterViewSpec.js, src/javascripts/test/karma.conf.js, src/javascripts/test/unit/Crud/field/maChoiceFieldSpec.js, src/javascripts/test/unit/Crud/field/maChoicesFieldSpec.js, src/javascripts/vendors.js, src/sass/ng-admin.scss, webpack.config.js
It adds select filtering and a better UI for multi-selects.
**Before:**
**Now:**
It will especially be useful to populate live select lists using AJAX requests.
**Tasks:**
=> [RFR] Use UI-Select for Choice and Choices fields

src/javascripts/ng-admin/Crud/column/maDateColumn.js, src/javascripts/ng-admin/Crud/field/maDateField.js, src/javascripts/ng-admin/Crud/misc/EntryFormatter.js
Depends on [admin-config#15](https://github.com/marmelab/admin-config/pull/15)
Date format can't be shared with other projects as the formatting is done by [angular](https://docs.angularjs.org/api/ng/filter/date).
=> [RFR] Set default format in date fields

Makefile
Issue especially happens when the folder `examples/blog/build` doesn't exist. Linux created it automatically, but not MacOS.
=> Update build to fix issues on MacOS (fixes #515)

package.json, src/javascripts/ng-admin/Crud/CrudModule.js, src/javascripts/ng-admin/Crud/field/datepickerPopup.js, src/javascripts/ng-admin/Crud/field/maDateField.js, src/javascripts/test/karma.conf.js, src/javascripts/test/unit/Crud/field/maDateFieldSpec.js
Fixes #520 ([known issue on Angular Bootstrap](https://github.com/angular-ui/bootstrap/issues/2659)).
=> [RFR] Fix default date format in date field

src/javascripts/ng-admin/Crud/button/maBackButton.js, src/javascripts/ng-admin/Crud/button/maBatchDeleteButton.js, src/javascripts/ng-admin/Crud/button/maCreateButton.js, src/javascripts/ng-admin/Crud/button/maDeleteButton.js, src/javascripts/ng-admin/Crud/button/maEditButton.js, src/javascripts/ng-admin/Crud/button/maExportToCsvButton.js, src/javascripts/ng-admin/Crud/button/maFilteredListButton.js, src/javascripts/ng-admin/Crud/button/maListButton.js, src/javascripts/ng-admin/Crud/button/maShowButton.js, src/javascripts/ng-admin/Crud/button/maViewBatchActions.js
View action buttons (create, export, filter, etc.) used to be glued to one another in the production environment (because of uglifyjs compression of html whitespace), but not in dev - that's why it went unnoticed for so long.
While fixing the problem, I also rewrote the templates of the buttons directives with the ES6 template literal syntax.
Before:
After:
=> [RFR] Add space between view action buttons

Gruntfile.js, README.md, UPGRADE-0.8.md, doc/API-mapping.md, examples/blog/config.js, examples/blog/stub-server.json, package.json, src/javascripts/ng-admin/Crud/button/maExportToCsvButton.js, src/javascripts/ng-admin/Crud/field/maField.js, src/javascripts/ng-admin/Crud/form/FormController.js, src/javascripts/ng-admin/Crud/list/ListController.js, src/javascripts/ng-admin/Crud/routing.js, src/javascripts/ng-admin/Main/config/routing.js, src/javascripts/test/e2e/EditionViewSpec.js, src/javascripts/test/unit/Main/component/service/config/view/ListViewSpec.js
Currently, callbacks registered on fields with `map()` are applied to the REST response to turn it into an Entry (when fetching results) AND to the entries to turn them into a response (when pushing modifications). It doesn't make sense, and prevents some new features, such as deeply nested fields (refs. #525).
This PR fixes that. Now you can do things like:
```js
listView.fields([
nga.field('title'),
nga.field('author.name')
]);
```
to map REST responses looking like:
```json
[
{
"title": "War and Peace",
"author": {
"name": "Leo Tolstoi"
}
},
{
"title": "Anna Karenina",
"author": {
"name": "Leo Tolstoi"
}
}
]
```
Depends on https://github.com/marmelab/admin-config/pull/20
=> [RFR] Clarify Map logic, allow nested fields

src/javascripts/ng-admin/Crud/repository/ReferenceRefresher.js, src/javascripts/test/unit/Crud/repository/ReferenceRefresherSpec.js
Fixing an issue found while debugging with @manuelnaranjo on [Gitter].
To prevent duplicates in multiple choices field, we remove already selected values from API responses. It works well for `reference_many` fields, but not for `reference` one. This PR disable deduplication for single choice fields.
=> [RFR] Do not deduplicate single choice remote complete fields

examples/blog/config.js, src/javascripts/ng-admin/Crud/field/maReferenceManyField.js, src/javascripts/test/unit/Crud/field/maReferenceManyFieldSpec.js
=> [RFR] Fix reference_many field when value is []

examples/blog/config.js, src/javascripts/ng-admin/Crud/column/maColumn.js, src/javascripts/test/e2e/EditionViewSpec.js, src/javascripts/test/e2e/ShowViewSpec.js
This PR is absolutely analogous to https://github.com/marmelab/ng-admin/pull/537
This time isDetailLink() applied to `referenced_list` entity doesn't work because of state parameter override.
I've created a e2e-test to demonstrate it. Test fails on your master branch, and passes on my commit.
=> [RFR] isDetailView doesn't work on refernced_list entity id-field

src/javascripts/ng-admin/Crud/delete/DeleteController.js, src/javascripts/test/e2e/ListViewSpec.js
If I press `Cancel` in *delete view* I want to go back where I came from, not to the deleted object's *edit view* (the delete button may be pressed in *list view* or in `referenced_list` field of other entity, not always in *edit view*; also *list view* or *edit view* or both may be disabled for deleted entity - than we would have an error). Same thing with after-delete-redirect.
I think it is much more logical to just redirect user to the previous entry in history, than to specifically *edit view* or *list view*. Is there some problems with this approach? I don't see any.
=> [RFR] Delete view: back to previous state, not edit or list view

README.md, UPGRADE-0.8.md, examples/blog/config.js, package.json
```js
posts.listView().permanentFilters({
published: true
});
// calls to the API will be GET /posts?published=true
```
Closes #548
=> [RFR] Add permanent filters

README.md, examples/blog/config.js, package.json
Before:
```js
nga.field('post_id', 'reference')
.label('Post')
.targetEntity(post)
.targetField(nga.field('title'))
.remoteComplete(true, { refreshDelay: 200 })
.permanentFilters(function(search) { return search ? { q: search } : null; })
```
After:
```js
nga.field('post_id', 'reference')
.label('Post')
.targetEntity(post)
.targetField(nga.field('title'))
.remoteComplete(true, {
refreshDelay: 200,
searchQuery: function(search) { return { q: search }; }
})
```
=> [RFR] Update remoteComplete API for better configurability

src/javascripts/ng-admin/Crud/field/maButtonField.js, src/javascripts/ng-admin/Crud/field/maCheckboxField.js, src/javascripts/ng-admin/Crud/field/maFileField.js, src/javascripts/ng-admin/Crud/field/maInputField.js, src/javascripts/ng-admin/Crud/field/maJsonField.js, src/javascripts/ng-admin/Crud/field/maTextField.js, src/javascripts/test/unit/Crud/field/maInputFieldSpec.js
=> [RFR] Fix custom attributes on fields

src/javascripts/ng-admin/Crud/field/maInputField.js, src/javascripts/ng-admin/Crud/field/maTextField.js
```js
user.creationView().fields([
nga.field('name')
.validation({ required: true, minlength: 3, maxlength: 100 }),
nga.field('username')
.attributes({ placeholder: 'No space allowed, 5 chars min' })
.validation({ required: true, pattern: '[A-Za-z0-9\.\-_]{5,20}' }),
])
```
=> Add support for pattern validation

doc/Configuration-reference.md, package.json, src/javascripts/ng-admin/Crud/field/maFileField.js
=> [RFR] Fix file field

doc/Configuration-reference.md, examples/blog/config.js, package.json, src/javascripts/ng-admin/Crud/column/maBooleanColumn.js, src/javascripts/ng-admin/Crud/field/maChoiceField.js, src/javascripts/ng-admin/Crud/fieldView/BooleanFieldView.js, src/javascripts/test/e2e/EditionViewSpec.js
=> [RFR] Make the boolean type handle null values

.travis.yml, Makefile, README.md, package.json
Less WTF for new devs, refs https://github.com/marmelab/ng-admin/issues/631#issuecomment-136641774
=> [RFR] Use local grunt instead of global

doc/Custom-types.md
=> [RFR] Better explain custom types

src/javascripts/ng-admin/Main/component/provider/NgAdminConfiguration.js
It becomes possible to recuperate a field constructor without installing the `admin-config` module:
```
var NumberField = nga.getFieldConstructor('number');
// now create a new class extending NumberField
function AmountField(name) {
NumberField.call(this, name)
}
AmountField.prototype = new NumberField();
AmountField.prototype.constructor = AmountField;
// or something like that
```
=> [RFR] Expose field constructors to avoid Webpack/Babel fuss

examples/blog/config.js, src/javascripts/ng-admin/Crud/CrudModule.js, src/javascripts/ng-admin/Crud/column/maReferencedListColumn.js, src/javascripts/ng-admin/Crud/field/maField.js, src/javascripts/ng-admin/Crud/fieldView/ReferencedListFieldView.js, src/javascripts/ng-admin/Crud/show/show.html
=> [RFR] Fix referenced_list loses detailLink when using new entity

examples/blog/config.js, src/javascripts/ng-admin/Crud/field/maField.js, src/javascripts/ng-admin/Crud/list/maDatagrid.js, src/javascripts/ng-admin/Crud/show/show.html, src/javascripts/test/e2e/ShowViewSpec.js
There was no way to style an entire column (header and cells), e.g. to hide a column in smaller screens. It's now possible.
=> [RFR] Apply cssClasses both to th and td in listView

src/sass/ng-admin.scss
=> Align number fields right in the datagrid

src/javascripts/ng-admin/Crud/button/maBackButton.js, src/javascripts/ng-admin/Crud/button/maBatchDeleteButton.js, src/javascripts/ng-admin/Crud/button/maCreateButton.js, src/javascripts/ng-admin/Crud/button/maDeleteButton.js, src/javascripts/ng-admin/Crud/button/maEditButton.js, src/javascripts/ng-admin/Crud/button/maExportToCsvButton.js, src/javascripts/ng-admin/Crud/button/maListButton.js, src/javascripts/ng-admin/Crud/button/maShowButton.js, src/javascripts/ng-admin/Crud/delete/delete.html, src/javascripts/ng-admin/Crud/filter/maFilterButton.js, src/javascripts/ng-admin/Crud/form/create.html, src/javascripts/ng-admin/Crud/form/edit.html, src/javascripts/ng-admin/Crud/list/listLayout.html, src/javascripts/ng-admin/Crud/show/show.html, src/sass/ng-admin.scss
=> [RFR] Make view actions more responsive

examples/blog/config.js, package.json, src/javascripts/ng-admin/Crud/delete/DeleteController.js, src/javascripts/test/e2e/ListViewSpec.js, src/javascripts/test/unit/Crud/delete/DeleteControllerSpec.js
Needs to implement and fix tests.
Closes #641.
=> [RFR] Return to list view when deleting a record

package.json, src/javascripts/ng-admin/Crud/CrudModule.js, src/javascripts/ng-admin/Crud/button/maExportToCsvButton.js, src/javascripts/ng-admin/Crud/column/maReferenceColumn.js, src/javascripts/ng-admin/Crud/column/maReferencedListColumn.js, src/javascripts/ng-admin/Crud/fieldView/ReferenceFieldView.js, src/javascripts/ng-admin/Crud/list/list.html, src/javascripts/ng-admin/Crud/list/maDatagrid.js, src/javascripts/ng-admin/Crud/list/maDatagridController.js, src/javascripts/ng-admin/Crud/routing.js, src/javascripts/ng-admin/Main/component/controller/DashboardController.js, src/javascripts/ng-admin/Main/component/directive/maDashboardPanel.js, src/javascripts/ng-admin/Main/config/routing.js, src/javascripts/ng-admin/Main/view/dashboard.html, src/javascripts/test/unit/Crud/list/DatagridControllerSpec.js
=> [RFR] Preload references in refrenced_list entries

doc/Configuration-reference.md, examples/blog/config.js, src/javascripts/ng-admin/Crud/list/maDatagrid.js
=> [RFR] Fix invalid reference to entry in datagrid header

doc/API-mapping.md, examples/blog/config.js
By default, ng-admin uses filters to fetch entities related to another one. For instance, to fetch all the `comments` related to the `post` entity #123, ng-admin calls the following url:
```
http://[baseApiUrl]/comments?filters={"post_id":123}
```
Some API servers only support a special type of URL for that case:
```
http://[baseApiUrl]/posts/123/comments
```
Restangular doesn't allow to modify the URL of an outgoing request (see [Restangular issue #603](https://github.com/mgonto/restangular/issues/603)), so in order to achieve that you must use an interceptor on the `$http` Angular service.
```js
myApp.config(['$httpProvider', function($httpProvider) {
$httpProvider.interceptors.push(function() {
return {
request: function(config) {
// test for /comments?filters={post_id:XXX}
if …
```
=> [RFR] Document the way to define nested entity urls for relationships

doc/Configuration-reference.md, examples/blog/config.js, package.json, src/javascripts/ng-admin/Crud/column/maBooleanColumn.js, src/javascripts/ng-admin/Crud/fieldView/BooleanFieldView.js, src/javascripts/test/e2e/EditionViewSpec.js, src/javascripts/test/unit/Crud/column/maBooleanColumnSpec.js, src/javascripts/test/unit/Crud/field/maCheckboxFieldSpec.js, src/javascripts/test/unit/Crud/fieldView/BooleanFieldView.js
=> [RFR] Required boolean fields use a checkbox for edition instad of a dropdown

src/javascripts/ng-admin/Crud/list/ListController.js
=> [RFR] infinitePagination now resolve reference fields

examples/blog/config.js, src/javascripts/ng-admin/Crud/list/ListLayoutController.js
```js
listView.filters([
nga.field('q')
.label('')
.pinned(true)
.template('<div class="input-group"><input type="text" ng-model="value" placeholder="Search" class="form-control"></input><span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span></div>')
.transform(v => v && v.toUpperCase()) // transform the entered value before sending it as a query parameter
.map(v => v && v.toLowerCase()), // map the query parameter to a displayed value in the filter form
])
```
=> [RFR] Make Field.transform() work on filters

Makefile, src/javascripts/ng-admin/Crud/field/maCheckboxField.js, src/javascripts/ng-admin/Crud/fieldView/BooleanFieldView.js, src/javascripts/test/e2e/EditionViewSpec.js
=> [RFR] Fix checkbox field

.jshintrc, doc/Configuration-reference.md, examples/blog/config.js, examples/blog/data.js, examples/blog/fakerest-init.js, examples/blog/index.html, package.json, src/javascripts/ng-admin/Crud/CrudModule.js, src/javascripts/ng-admin/Crud/column/maEmbeddedListColumn.js, src/javascripts/ng-admin/Crud/column/maReferencedListColumn.js, src/javascripts/ng-admin/Crud/config/factories.js, src/javascripts/ng-admin/Crud/field/maEmbeddedListField.js, src/javascripts/ng-admin/Crud/fieldView/DateFieldView.js, src/javascripts/ng-admin/Crud/fieldView/DateTimeFieldView.js, src/javascripts/ng-admin/Crud/fieldView/EmbeddedListFieldView.js, src/javascripts/ng-admin/Crud/list/maDatagrid.js, src/javascripts/ng-admin/Crud/list/maDatagridController.js, src/javascripts/test/e2e/EditionViewSpec.js, src/javascripts/test/e2e/ShowViewSpec.js, src/javascripts/test/unit/Crud/column/maEmbeddedListColumnSpec.js, src/javascripts/test/unit/Crud/field/maEmbeddedListFieldSpec.js, src/javascripts/test/unit/Crud/list/DatagridControllerSpec.js, src/sass/ng-admin.scss
The new `embedded_list` type maps an array of objects inside an entry, e.g.
```json
{  
"id":1,
"title":"Accusantium qui nihil voluptatum quia voluptas maxime ab similique",
"comments":[  
{  
"author":{  
"name":"Edmond Schulist"
},
"body":"I ought to tell me your history, you know,' the Hatter and the happy summer days. THE.",
"created_at":"2012-08-07"
},
{  
"author":{  
"name":"Logan Schowalter"
},
"body":"I don't want to be?' it asked. 'Oh, I'm not Ada,' she said, 'and see whether it's marked \"poison\" or not'; for she had asked it aloud; and in despair she put her hand on the end of the.",
"created_at":"2012-08-05"
}
]
}
```
You can now map the `comments` field:
```js
posts.showView().fields([
nga.field('id'),
nga.field('title'),
nga.field('comments', 'embedded_list') …
```
=> [RFR] Introducing the embedded_list field type

src/javascripts/ng-admin/Crud/column/maColumn.js
=> fix - JS error "values of undefined" on a missing reference in a column

doc/Custom-types.md, doc/reference/View.md, examples/blog/config.js, package.json, src/javascripts/ng-admin/Crud/CrudModule.js, src/javascripts/ng-admin/Crud/column/maReferenceColumn.js, src/javascripts/ng-admin/Crud/routing.js, src/javascripts/test/e2e/ListViewSpec.js
`view.prepare(Function)` adds a function to be executed before the view renders.
This is the ideal place to prefetch related entities and manipulate the DataStore. The function can be asynchronous, in which case it should return a Promise.
The `prepare` function is invoked using Angular's dependency injection system, with a context offering the following services:
- `query`: the query object (an object representation of the main request query string)
- `datastore`: where the Entries are stored. The dataStore is accessible during rendering
- `view`: the current View object
- `entry`: the current Entry instance (except in listView)
- `entries`: the current list of Entry instances (only in listView)
- `Entry`: the Entry constructor (required to transform an object from the REST response to …
=> [RFR] Add support for the `View.prepare()` logic

src/javascripts/ng-admin/Crud/routing.js
- router's prepare injected 'entry', passed in `entries`,
and used `entry`, changed so that they are all consistently 'entry'
=> Fix typo in arguments to prepare in router

doc/reference/Field.md, package.json, src/javascripts/ng-admin/Crud/fieldView/BooleanFieldView.js, src/javascripts/ng-admin/Crud/list/ListLayoutController.js, src/javascripts/test/unit/Crud/fieldView/BooleanFieldView.js
For `boolean` Field Type, add the `filterChoices(array)` method. It expects an array of choices used for the boolean proposed values in a filter. By default:
[
{ value: true, label: 'true' },
{ value: false, label: 'false' }
]
Override it with custom labels to fit your needs:
nga.fields('power_user', 'boolean')
.filterChoices([
{ value: true, label: 'enabled' },
{ value: false, label: 'disabled' }
]);
=> [RFR] Allow boolean filter labels to be overridden

src/javascripts/ng-admin/Crud/show/maShowItem.js
Use separate block to specify CSS classes in show item view.
This is required to cope with a bug found in webkit-based browsers (e.g. Chrome, Safari) which produced a corrupt highlighted text upon both double-click and triple-click selection.
=> Fix double-click selection bug in webkit browsers

package.json, src/javascripts/ng-admin/Crud/column/maReferencedListColumn.js
requires: marmelab/admin-config/pull/55
=> Add entryCssClasses functionality to referenced list field.

src/javascripts/ng-admin/Crud/button/maExportToCsvButton.js, src/javascripts/ng-admin/Crud/list/listLayout.html, src/javascripts/ng-admin/Crud/misc/ViewActions.js
exportToCsv function was failing to correctly reload data in a new filtered page. This was due to an incorrect search parameters given to the ReadQueries getAll function. Using $stateParams' search
attribute (instead of scope.search()) solves the issue.
Fix ng-admin issue #738.
=> Reload export data when list is (re)filtered

src/javascripts/ng-admin/Crud/routing.js
prepare() was called at the end of the resolve list, but wasn't executed
last in the chain because of loose dependencies.
=> [RFR] Fix prepare() doesn't get fully populated datastore

doc/FAQ.md, doc/reference/View.md, package.json, src/javascripts/ng-admin/Crud/form/FormController.js
Closes #805, #862, #782, #777.
See updated doc for details.
=> [RFR] Add edition and creation hooks

examples/blog/fakerest-init.js
When I'm doing `make run` -  my Chromium devTools Console got flooded by "[WDS] Disconnected!" messages sent within interval of 2 seconds.
I've investigated the issue and found out that the problem is caused by `SinonJS` which intercepts WebSocket requests to `webpack-dev-server`. This is because `webpack-dev-server` recently [moved from Socket.io to SockJS](https://github.com/webpack/webpack-dev-server/pull/302), so now WebSocket requests are sent  not to `/socket.io/` path, but to the `/sockjs-node/` path.
=> [RFR] Fix webpack-dev-server web-socket error

doc/reference/View.md, examples/blog/config.js, package.json, src/javascripts/ng-admin/Crud/button/maExportToCsvButton.js
Customize the CSV export format (quotes, delimiter, newline). The default options object is `{ quotes: false, delimiter: ",", newline: "\r\n" }`.
listView.exportOptions({
quotes: true,
delimiter: ';'
});
=> [RFR] Add ability to customize CSV export format

src/javascripts/ng-admin/Crud/list/maDatagridPagination.html, src/javascripts/test/unit/Crud/list/maDatagridPaginationSpec.js
I noticed what I believe to be a typo in the text on the frontend which specifies what items are being shown and the total amount of items. Currently the pagination area reads something like "1-10 on 15" when I think it should be "1-10 **of** 15." I updated the frontend code and the testing files to this effect.
=> fixing frontend pagination typo from '1-10 on 15' to '1-10 of 15'

doc/Production.md, package.json, src/javascripts/ng-admin/Crud/CrudModule.js, src/javascripts/ng-admin/Crud/button/maViewBatchActions.js, src/javascripts/ng-admin/Crud/field/datepickerPopup.js, src/javascripts/ng-admin/Crud/field/maDateField.js, src/javascripts/ng-admin/Crud/filter/maFilterButton.js, src/javascripts/test/karma.conf.js, src/javascripts/test/unit/Crud/field/maDateFieldSpec.js, src/javascripts/vendors.js
=> [RFR] Update ui-bootstrap

src/javascripts/ng-admin/Main/view/menuBar.html
The upgrade of Angular UI changed the `collapse` directive name to `uib-collapse`.
Fixes #962
=> [RFR] Fix mobile menu toggle

UPGRADE-1.0.md, examples/blog/config.js, src/javascripts/ng-admin/Crud/form/FormController.js, src/javascripts/ng-admin/Crud/routing.js, src/javascripts/test/e2e/EditionViewSpec.js
Change default behavior after form submission:
- Creation form submit => show view (if exists) or list view
- Edition form submit => previous page (if exists) or stays on edition form
Previous behavior was:
- Creation form submit => edition view or show view (if exists)
- Edition form submit => stays on edition form
=> [RFR] Change referring target after form submit

doc/Custom-types.md
Without the type, the AmountFieldView is not used,
ng-admin uses the inherited NumberFieldView
=> Document setting the type for the field

src/javascripts/ng-admin/Crud/routing.js
Patch for #871 (EditView, not ListView)
=> Added missing EditView.getUrl parameter

doc/FAQ.md
The sentence `Since there a are two fields names user_id, it's a blocker.` seems to be wrong ;)
=> Error in documentation

src/javascripts/ng-admin/Crud/form/FormController.js
There was a missing 'this' keyword using the notification service in one of the FormController methods.
=> Fixed reference to 'notification' service

src/sass/ng-admin.scss
Not just the `label-default`
before:
after:
=> [RFR] In datagrids, apply label styles to all labels

src/javascripts/ng-admin/Crud/delete/BatchDeleteController.js, src/javascripts/ng-admin/Crud/delete/DeleteController.js, src/javascripts/ng-admin/Crud/form/FormController.js, src/javascripts/test/unit/Crud/delete/DeleteControllerSpec.js
=> [RFR] Display progress bar when deleting

ISSUE_TEMPLATE.md
First draft of an issue template re #1157
=> #1157 add an issue template with a request for Plunkr repro steps

README.md, UPGRADE-1.0.md, doc/Custom-pages.md, examples/blog/config.js, examples/blog/index.html, src/javascripts/ng-admin/Crud/routing.js, src/javascripts/ng-admin/Main/config/routing.js
I don't think we can configure the view name, since the routing executes before we can access the configuration...
Closes #335, #446, #730
=> [BC BREAK] [RFR] Rename main view to ng-admin

README.md, src/javascripts/ng-admin/Crud/field/maChoiceField.js, src/javascripts/test/unit/Crud/field/maChoiceFieldSpec.js
=> [RFR] Update select choices whenever entry changes

package.json
Since the folder is renamed, the package.json file have been updated (https://github.com/marmelab/ng-admin/pull/1189/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R14) but not its `main` attribute.
=> [RFR] Fix npm main source

src/javascripts/ng-admin/Crud/list/ListController.js, src/javascripts/ng-admin/Crud/list/maDatagridInfinitePagination.js, src/javascripts/test/unit/Crud/list/maDatagridInfinitePaginationSpec.js
Fix infinite scrolling list view :
=> [RFR] Fix infinite scrolling request synchronization

doc/Getting-started.md
Remove the note abut nonexistent entity being created automatically
Fix the getting started code
=> Fix Getting started code and documentation

package.json, src/javascripts/ng-admin/Crud/list/ListLayoutController.js, src/javascripts/vendors.js
As discussed with @fzaninotto, reopening this PR. I have left the original implementation with a global delcared in the vendor.js since this is the solution I tested.
On latest build I am getting the error _.includes is not a function when navigating into one of my custom pages.
Following several threads on Restangular Git (one of them being mgonto/restangular#1225). I found out that Restangular is now compatible with lodash 4.
ng-admin using underscore is causing incompatibilty since the new webpack dependency version has been merged. Making use of lodash fixes the problems
=> Use lodash instead of underscore

_postinstall.js, package.json
Follow up on E2E fix commit, so the npm postinstall phase also work on Windows node installations
Rebase of https://github.com/marmelab/ng-admin/pull/1266
=> Npm post install for windows

doc/Getting-started.md
deleted one extra "achieve" at doc.
=> [FIX] typo in Doc

src/javascripts/ng-admin/Crud/field/maEmbeddedListField.js, src/javascripts/test/unit/Crud/field/maEmbeddedListFieldSpec.js
=> [RFR] Use field label for embedded list add button

src/javascripts/ng-admin/Crud/list/ListLayoutController.js, src/javascripts/test/unit/Crud/field/maEmbeddedListFieldSpec.js
Because of this, depending of how fast user was typing its search filter, some of its characters were overriden with the previous search.
=> [RFR] Fix filter which was overwriting url after a change

Makefile, scripts/check-only-in-tests.sh
In order to avoid `fit`, `fdescribe` or `.only` on master.
=> [RFR] Check for fit, fdescribe or .only in tests

Makefile, package.json
@Phocea We are forced to do it this way since the `_postinstall.js` file is excluded from the NPM build.
=> [RFR] Remove selenium installation from post install hook

Makefile
ATM there are no sourcemaps available, what is quite a pain to debug. It seems as if they were intended to exist in the first place.
The command in the Makefile is slightly different to really get sourcemaps for the `ng-admin.min.js` and `ng-admin.min.css` files.
=> Makefile: Fix generating source-map with webpack

doc/Theming.md, src/javascripts/ng-admin/Crud/delete/DeleteController.js, src/javascripts/ng-admin/Crud/form/FormController.js, src/javascripts/ng-admin/Main/component/provider/HttpErrorService.js, src/javascripts/ng-admin/Main/config/translate.js, src/javascripts/ng-admin/Main/run/HttpErrorHandler.js, src/javascripts/test/unit/Main/component/provider/HttpErrorServiceTest.spec.js
This PR is aim to make use of the new HttpErrorService to display CRUD form http error responses.
For backward compatibility, the code still pick up customization done via [entity.errorMessage method](https://github.com/marmelab/ng-admin/blob/Handle-Crud-Form-Error-Through-HttpErrorService/doc/Theming.md#customizing-error-messages). However this step is now redudant since it can be done inside an decorator
=> [RFR] Handle CRUD form error through http error service

Makefile, src/javascripts/ng-admin/Crud/field/maDateField.js, src/javascripts/test/unit/Crud/field/maDateFieldSpec.js
Related to #1271
Fix #1305
Supersede #1317
=> [RFR] Fix DateField watches

src/javascripts/ng-admin/Crud/list/ListLayoutController.js, src/javascripts/test/unit/Crud/field/maEmbeddedListFieldSpec.js
Reverts marmelab/ng-admin#1290
Because this fix creates a new bug: #1328. We need a different way to fix the bug.
=> Revert "[RFR] Fix filter which was overwriting url after a change"

src/javascripts/ng-admin/Crud/field/maDateField.js, src/javascripts/test/unit/Crud/field/maDateFieldSpec.js
=> [RFR] Do not update date field actual value if invalid

CHANGELOG.md, examples/blog/config.js, package.json
It should fix the disabling of views which wasn't working when you had fields initialized inside the view.
It also fix the test fixtures which were making tags a read only entity and trying to go to its edit page anyway.
=> [RFR] Fix disabling views

src/javascripts/ng-admin/Crud/delete/BatchDeleteController.js, src/javascripts/ng-admin/Crud/delete/DeleteController.js, src/javascripts/ng-admin/Crud/delete/batchDelete.html, src/javascripts/ng-admin/Crud/delete/delete.html, src/javascripts/ng-admin/Crud/form/FormController.js, src/javascripts/test/unit/Crud/delete/BatchDeleteControllerSpec.js, src/javascripts/test/unit/Crud/delete/DeleteControllerSpec.js, src/javascripts/test/unit/Crud/form/FormControllerSpec.js
The `HttpErrorService` decorator wasn't working on view like on "Submit changes".
It should now work.
Still untested, need some more work.
=> [RFR] Use http error service handlers inside view events

src/javascripts/ng-admin/Crud/list/ListLayoutController.js, src/javascripts/test/unit/Crud/list/ListLayoutControllerSpec.js
Fixes an issue where a pinned filter wouldn't filter with its initially selected value.
=> [RFR] Update filters on view initialization

src/javascripts/ng-admin/Crud/list/maDatagridInfinitePagination.js, src/javascripts/test/unit/Crud/list/maDatagridInfinitePaginationSpec.js
When scrolling to the bottom of the page, ng-admin was sending way too many requests and didn't debounce anything.
=> [RFR] Debounce scroll events
