Makefile
README.md

Document build-dev make command

---

src/javascripts/ng-admin/Main/MainModule.js
src/javascripts/ng-admin/Main/component/controller/SidebarController.js
src/javascripts/ng-admin/Main/component/filter/Enabled.js
src/javascripts/ng-admin/Main/component/service/PanelBuilder.js
src/javascripts/ng-admin/Main/component/service/config/Entity.js
src/javascripts/ng-admin/Main/component/service/config/view/MenuView.js

Closes #206 
I also took the advantage to use the same kind of code for the menuView as for the dashboardView for ordering and disabling.

[RFR] Fix dashboardView.disable()

---

src/javascripts/ng-admin/Crud/column/maColumn.js
src/javascripts/ng-admin/Main/MainModule.js
src/javascripts/ng-admin/Main/component/filter/StripTags.js
src/javascripts/test/unit/Main/component/filter/StripTagsSpec.js

[RFR] Strip tags in list wysiwyg fields

---

README.md
src/javascripts/ng-admin/Crud/list/DatagridController.js
src/javascripts/ng-admin/Crud/repository/RetrieveQueries.js
src/javascripts/ng-admin/Main/component/service/config/view/ListView.js

Using Restangular interceptors for that feels verbose and weird.

[RFR] Readd the ability to customize sort per entity

---

src/javascripts/ng-admin/Crud/list/maDatagridPagination.js

[RFR] Remove scroll listener on infinite pagination destroy

---

doc/Theming.md
src/javascripts/ng-admin/Crud/form/FormController.js
src/javascripts/ng-admin/Main/component/service/config/Application.js
src/javascripts/ng-admin/Main/component/service/config/Entity.js
src/javascripts/ng-admin/Main/component/service/config/view/View.js
src/javascripts/test/unit/Main/component/service/config/ApplicationSpec.js

[RFR] Allows to customize error messages

---

src/javascripts/ng-admin/Crud/repository/RetrieveQueries.js

`filters` are in 3rd position in the declaration of `getRawValues`.
Fixes #229

[RFR] Fix getRawValues params order

---

doc/Theming.md
src/javascripts/ng-admin/Main/component/service/config/Application.js
src/javascripts/ng-admin/Main/config/routing.js

[RFR] Allow overriding the main layout

---

examples/blog/config.js
src/javascripts/ng-admin/Crud/filter/maFilter.html
src/javascripts/ng-admin/Crud/form/FormController.js
src/javascripts/ng-admin/Crud/form/create.html
src/javascripts/ng-admin/Crud/form/edit.html
src/javascripts/ng-admin/Crud/list/Datagrid.html
src/javascripts/ng-admin/Crud/list/ListController.js
src/javascripts/ng-admin/Crud/show/ShowController.js
src/javascripts/ng-admin/Crud/show/show.html
src/javascripts/test/unit/Crud/list/maDatagridSpec.js

Because AngularJS execute the filter 2 times on the two way binding process.
Hard to say if it's a big improvement.

[RFR] Avoid using filter on ng-repeat

---

Gruntfile.js
examples/blog/config.js
src/javascripts/ng-admin/Crud/filter/maFilter.html
src/javascripts/ng-admin/Crud/list/ListController.js
src/javascripts/ng-admin/Crud/repository/RetrieveQueries.js
src/javascripts/ng-admin/Crud/routing.js
src/javascripts/ng-admin/Main/component/service/config/view/ListView.js
src/javascripts/test/e2e/filterViewSpec.js
src/javascripts/test/unit/Crud/repository/RetrieveQueriesSpec.js
src/sass/ng-admin.scss

[RFR] Allow ListView filters on references

---

README.md
src/javascripts/ng-admin/Crud/repository/RetrieveQueries.js
src/javascripts/ng-admin/Main/component/service/config/Reference.js
src/javascripts/ng-admin/Main/component/service/config/ReferenceMany.js
src/javascripts/ng-admin/Main/component/service/config/ReferencedList.js

Reverts hotfix 9b600387251541191aa6cac3512def87e88eb4ce and
5c44936d7d590e6f2fe65d9b94bf304858682ae0
I also cleaned up the inheritance of fields and references, which was buggy.

[RFR] Allow Embedded datagrids to be limited

---

src/javascripts/ng-admin/Crud/column/maColumn.js
src/javascripts/ng-admin/Crud/delete/delete.html
src/javascripts/ng-admin/Crud/form/create.html
src/javascripts/ng-admin/Crud/form/edit-attribute.html
src/javascripts/ng-admin/Crud/form/edit.html
src/javascripts/ng-admin/Crud/list/list.html
src/javascripts/ng-admin/Crud/show/show.html
src/javascripts/test/e2e/referenceSpec.js

Closes #247, introduced by #240

[RFR] Fix ReferencedList field order

---

src/javascripts/ng-admin/Crud/form/edit-attribute.html
src/javascripts/ng-admin/Crud/routing.js
src/javascripts/test/e2e/referenceSpec.js

[RFR] Fix ordering problems in ReferenceFields

---

src/javascripts/ng-admin/Crud/delete/delete.html
src/javascripts/ng-admin/Crud/form/create.html
src/javascripts/ng-admin/Crud/form/edit.html
src/javascripts/ng-admin/Crud/list/list.html
src/javascripts/ng-admin/Crud/show/show.html
src/javascripts/ng-admin/Main/view/dashboard.html
src/javascripts/ng-admin/Main/view/layout.html
src/javascripts/test/e2e/spec.js
src/sass/ng-admin.scss

Use `?w=1` to see the real changes.

[RFR] Cleanup markup to adhere to the sb-admin standard

---

CHANGELOG.md

Each past release is [already documented](https://github.com/marmelab/ng-admin/releases), however it's currently cumbersome to keep track of all changes in the current version.

[RFR] Add changelog

---

README.md
doc/Custom-pages.md
examples/blog/config.js

Just added example and documentation to show what's possible

[RFR] Custom pages

---

src/javascripts/ng-admin/Main/component/directive/maDashboardPanel.js
src/javascripts/ng-admin/Main/view/dashboard-panel.html
src/sass/ng-admin.scss

I also took advantage to fix column ordering in the dashboard, and to fix pointer on links for the entire application.

[RFR] Dashboard panel titles now link to list view

---

src/javascripts/ng-admin/Crud/filter/maFilter.html

[RFR] Add more field types to filter

---

src/javascripts/ng-admin/Crud/form/FormController.js
src/javascripts/ng-admin/Crud/form/create.html
src/javascripts/ng-admin/Crud/form/edit-attribute.html
src/javascripts/ng-admin/Crud/form/edit.html
src/javascripts/ng-admin/Main/component/service/config/view/CreateView.js
src/javascripts/ng-admin/Main/component/service/config/view/EditView.js

[RFR] Fix form validation in create view

---

src/javascripts/ng-admin/Crud/form/edit-attribute.html

[RFR] Allow listActions in ReferenceList to show in editionView, too

---

src/javascripts/ng-admin/Crud/list/DatagridPaginationController.js
src/javascripts/ng-admin/Main/component/service/PanelBuilder.js
src/javascripts/test/unit/Main/component/service/PanelBuilderSpec.js

Refs #317.
Once merged, would it be possible to release a `0.6` version to embed the `nga.field` refactoring?

[RFR] Use entity label when no dashboard title is provided

---

README.md
src/javascripts/ng-admin/Crud/field/maWysiwygField.js
src/javascripts/ng-admin/es6/lib/Field/WysiwygField.js

WYSIWYG field sanitization can be enabled or disabled by field configuration.

WYSIWYG field sanitization enableable

---

src/javascripts/ng-admin/es6/lib/View/ListView.js
src/javascripts/test/function.bind.shim.js
src/javascripts/test/karma.conf.js

In WIP. Trying to identify the issue first.

[RFR] Fix Karma tests

---

src/javascripts/ng-admin/Crud/repository/RetrieveQueries.js

[RFR] Allow referenced_list to be orderd by configuration

---

src/javascripts/ng-admin/Crud/CrudModule.js
src/javascripts/ng-admin/Crud/delete/BatchDeleteController.js
src/javascripts/ng-admin/Crud/delete/DeleteController.js
src/javascripts/ng-admin/Crud/form/FormController.js

[RFR] Add missing notifications, make notifications last longer

---

src/javascripts/ng-admin/Crud/filter/maFilter.js
src/javascripts/ng-admin/Crud/filter/maFilterController.js

A missing `var` made the e2e tests fail with the latest Chrome Driver.

[RFR] Fix e2e tests

---

src/javascripts/ng-admin/Crud/routing.js
src/javascripts/ng-admin/Main/MainModule.js
src/javascripts/ng-admin/Main/config/routing.js
src/javascripts/ng-admin/Main/run/ErrorHandler.js
src/javascripts/ng-admin/Main/view/404.html
src/sass/ng-admin.scss

[RFR] Improve error handling

---

doc/Theming.md
examples/blog/config.js
src/javascripts/ng-admin/Main/component/controller/AppController.js
src/javascripts/ng-admin/Main/view/layout.html
src/javascripts/ng-admin/es6/lib/Application.js
src/sass/ng-admin.scss

[RFR] Add ability to customize the admin header

---

src/javascripts/ng-admin/Crud/field/maFileField.js

[RFR] Fix accept type in file field

---

src/sass/ng-admin.scss

The animation for the opening and closing submenu used to be clunky.
This PR fixes it.

[RFR] Fix accordion effect on sidebar menu

---

README.md
doc/Custom-pages.md

Fix documentation

---

README.md

[RFR] Fix typo in README

---

src/javascripts/ng-admin/Main/component/directive/maDashboardPanel.js

[RFR] Fix dashboard panel heading link

---

examples/blog/config.js
src/javascripts/ng-admin/Crud/field/maChoiceField.js
src/javascripts/ng-admin/Crud/field/maChoicesField.js
src/javascripts/test/e2e/filterViewSpec.js
src/javascripts/test/unit/Crud/field/maChoiceFieldSpec.js
src/javascripts/test/unit/Crud/field/maChoicesFieldSpec.js
src/sass/ng-admin.scss

[RFR] Make choice field required works and fix angular add empty first option

---

Gruntfile.js
src/javascripts/ng-admin/Crud/routing.js
src/javascripts/test/e2e/ListViewSpec.js

[RFR] Fix edit & show links

---

src/javascripts/test/e2e/ListViewSpec.js
src/javascripts/test/protractor.conf.js

Due to a serious issue concerning click on element, I had to skip concerning tests.
Those tests pass localy, but I can't find a correct solution to make it pass on saucelabs.
See https://code.google.com/p/selenium/issues/detail?id=2766 for more details on the bug.

[RFR] Fix ListView e2e tests

---

src/sass/ng-admin.scss

[RFR] Fix top margin regressions

---

README.md

[RFR] Fix outdated method name in doc

---

examples/blog/config.js
src/javascripts/ng-admin/Crud/fieldView/ReferencedListFieldView.js
src/javascripts/ng-admin/Main/component/controller/DashboardController.js
src/javascripts/ng-admin/Main/component/service/PanelBuilder.js
src/javascripts/test/e2e/ShowViewSpec.js

Fixes #478 
Need https://github.com/marmelab/admin-config/pull/4

[RFR] Fix sort for ReferenceListField and dashboard

---

src/javascripts/ng-admin/Crud/misc/RestWrapper.js

Hi,
this is the complement to marmelab/admin-config#8 and the 2nd approach for #451.
Let me know what you think.
Mats

added userdefined create and update HTTP Method

---

package.json
src/javascripts/ng-admin.js

[RFR] Add promise shim for some browsers (IE11, I'm watching you!)

---

src/javascripts/ng-admin/Main/component/directive/maMenuBar.js
src/javascripts/ng-admin/Main/view/menuBar.html

Closes #417 
I took advantage of this small patch to refactor the directive a little.

[RFR] Fix menu collapse on second click

---

Gruntfile.js

This one should make you happy @fzaninotto! ;)

[RFR] Webpack: be more quiet please

---

src/javascripts/ng-admin/Crud/list/ListController.js

Fix typo in infinite pagination controller

---

src/javascripts/ng-admin/Crud/routing.js

[RFR] Fix problem with multiple references on same entity

---

src/javascripts/ng-admin/Crud/column/maColumn.js

Should avoid any link to a non-existent state

[RFR] Clarify and fix the detailLink logic

---

src/javascripts/ng-admin/Crud/field/maChoiceField.js

[RFR] Allow placeholder to be overridden on choice fields

---

src/javascripts/ng-admin/Crud/field/maChoiceField.js
src/sass/ng-admin.scss

[RFR] Allow deselection to send null value in choice field

---

examples/blog/config.js
src/javascripts/ng-admin/Crud/field/maChoicesField.js

Fixes #626.
I copy/pasted some code from the Choice component. We may perhaps consider refactoring them to apply DRY principle (low priority yet).

[RFR] Allow to customize multiple choices placeholder

---

examples/blog/config.js
package.json
src/javascripts/ng-admin/Crud/button/maCreateButton.js
src/javascripts/ng-admin/Crud/button/maDeleteButton.js
src/javascripts/ng-admin/Crud/button/maEditButton.js
src/javascripts/ng-admin/Crud/button/maShowButton.js
src/javascripts/test/e2e/ShowViewSpec.js

This ability was lost when the configuration API was refactored to
admin-config.
Refs #269, #270

[RFR] (re)-add listActions support on referencedList

---

examples/blog/config.js
src/javascripts/ng-admin.js
src/javascripts/ng-admin/Crud/repository/ReferenceRefresher.js
src/javascripts/ng-admin/Crud/routing.js
src/javascripts/test/unit/Crud/repository/ReferenceRefresherSpec.js

Before:
```js
nga.field('post_id', 'reference')
.map(truncate) // doesn't make sense, we truncate a post_id???
.label('Post')
.targetEntity(post)
.targetField(nga.field('title'))
```
After:
```js
nga.field('post_id', 'reference')
.label('Post')
.targetEntity(post)
.targetField(nga.field('title').map(truncate))
```

[RFR] Fix inconsistency in remote reference map

---

src/javascripts/ng-admin/Crud/misc/view-actions.html

[RFR] allow to add filter when using custom actions

---

doc/Getting-started.md

Made a bad pull-request, so this is the correct one... Sorry :-(

Fixed the link to the configuration reference API

---

examples/blog/config.js
src/javascripts/ng-admin/Main/component/controller/AppController.js
src/javascripts/ng-admin/Main/view/layout.html
src/javascripts/ng-admin/Main/view/menuBar.html
src/javascripts/test/e2e/ListViewSpec.js

[RFR] Make dashboard responsive

---

src/javascripts/ng-admin/Crud/config/factories.js
src/javascripts/ng-admin/Crud/fieldView/DateTimeFieldView.js
src/sass/ng-admin.scss

Avoid truncating dates in editionView. Also, created 2 different widths for date and datetime.
Before:
After: 
Supersedes #573

[RFR] Fix date widget formatting

---

src/javascripts/ng-admin/Crud/list/ListLayoutController.js
src/javascripts/ng-admin/Crud/routing.js
src/javascripts/test/e2e/ListViewSpec.js

[RFR] Fix default filter glitch

---

examples/blog/config.js
package.json

Refs
https://github.com/marmelab/admin-config/commit/412e5ab3cd8cf117671eef0449624707fd2fb7ed

[RFR] Fix optimized queries

---

doc/Configuration-reference.md

Correct spelling error in Configuration-reference

---

examples/blog/config.js
src/javascripts/ng-admin/Crud/button/maBackButton.js
src/javascripts/ng-admin/Crud/button/maBatchDeleteButton.js
src/javascripts/ng-admin/Crud/button/maCreateButton.js
src/javascripts/ng-admin/Crud/button/maDeleteButton.js
src/javascripts/ng-admin/Crud/button/maEditButton.js
src/javascripts/ng-admin/Crud/button/maListButton.js
src/javascripts/ng-admin/Crud/button/maShowButton.js
src/javascripts/ng-admin/Crud/routing.js

`<ma-create-button entity-name="comments" default-values="{ post_id: entry.values.id }" size="xs"></ma-create-button>`
Closes #627

[RFR] Add default value parameter for create view and create-button directive

---

doc/Configuration-reference.md

Reference:targetLabel -> Reference:targetField

Doc: fixed bad method name (Reference:targetLabel)

---

doc/Configuration-reference.md

[RFR] Add doc on input date requirement for format

---

Gruntfile.js
Makefile
examples/blog/build/sinon-server.js
package.json

[RFR] Fixed Build & demo:

---

README.md

Just found another quick typo. - Hope this helps :)

Fix another broken link :)

---

src/sass/ng-admin.scss

[RFR] Fix UI select multi style

---

src/javascripts/ng-admin/Crud/misc/EntryFormatter.js

This was an old fix that for some reason I forgot to pull... I saw that in the new version, this still is not fixed, therefore here it is.
Ref #474

Support template field in CSV ExportFields list

---

UPGRADE-1.0.md
doc/Custom-types.md
doc/reference/Field.md
src/javascripts/ng-admin/Crud/CrudModule.js
src/javascripts/ng-admin/Crud/button/maCreateButton.js
src/javascripts/ng-admin/Crud/button/maDeleteButton.js
src/javascripts/ng-admin/Crud/button/maEditButton.js
src/javascripts/ng-admin/Crud/button/maFilteredListButton.js
src/javascripts/ng-admin/Crud/button/maListButton.js
src/javascripts/ng-admin/Crud/button/maShowButton.js
src/javascripts/ng-admin/Crud/column/maColumn.js
src/javascripts/ng-admin/Crud/column/maReferenceLinkColumn.js
src/javascripts/ng-admin/Crud/column/maReferenceManyLinkColumn.js
src/javascripts/ng-admin/Crud/fieldView/BooleanFieldView.js
src/javascripts/ng-admin/Crud/fieldView/ChoiceFieldView.js
src/javascripts/ng-admin/Crud/fieldView/ChoicesFieldView.js
src/javascripts/ng-admin/Crud/fieldView/DateFieldView.js
src/javascripts/ng-admin/Crud/fieldView/DateTimeFieldView.js
src/javascripts/ng-admin/Crud/fieldView/EmailFieldView.js
src/javascripts/ng-admin/Crud/fieldView/FloatFieldView.js
src/javascripts/ng-admin/Crud/fieldView/NumberFieldView.js
src/javascripts/ng-admin/Crud/fieldView/ReferenceFieldView.js
src/javascripts/ng-admin/Crud/fieldView/StringFieldView.js
src/javascripts/ng-admin/Crud/fieldView/TemplateFieldView.js
src/javascripts/ng-admin/Crud/fieldView/TextFieldView.js
src/javascripts/ng-admin/Crud/fieldView/WysiwygFieldView.js
src/javascripts/ng-admin/Main/component/directive/maMenuBar.js
src/javascripts/ng-admin/Main/view/menuBar.html
src/javascripts/test/unit/Crud/column/maColumnSpec.js
src/javascripts/test/unit/Main/component/directive/maMenuBarSpec.js

Allows to visualize links before they are clicked, middle-click to open in a new tab, copy the link, etc.
Closes #775

[RFR] Use ui-sref for links instead of ng-click

---

src/javascripts/ng-admin/Crud/field/maChoiceField.js
src/javascripts/ng-admin/Crud/field/maChoicesField.js

remote-complete issue - results are not set if term does not perfectly match part of the choice
- fixes #787

remote-complete filtering

---

src/javascripts/ng-admin/Crud/list/ListLayoutController.js
src/javascripts/test/e2e/filterViewSpec.js

[RFR] Fix navigation with slow API

---

src/javascripts/ng-admin/Crud/field/maChoiceField.js

Fix maChoiceField for Angular 1.4

---

doc/reference/View.md
examples/blog/config.js
src/javascripts/ng-admin/Crud/list/ListController.js
src/javascripts/ng-admin/Crud/list/list.html
src/javascripts/ng-admin/Crud/list/maDatagrid.js
src/javascripts/ng-admin/Crud/list/maDatagridController.js
src/javascripts/test/e2e/ListViewSpec.js

[RFR] Add variable cssClasses for the whole row in ListView

---

doc/Production.md
package.json

[RFR] Remove Lodash

---

src/javascripts/ng-admin/Crud/delete/delete.html
src/javascripts/ng-admin/Crud/form/create.html
src/javascripts/ng-admin/Crud/form/edit.html
src/javascripts/ng-admin/Crud/list/listLayout.html
src/javascripts/ng-admin/Crud/show/show.html

[RFR] Use entity label instead of name for view titles

---

Gruntfile.js
Makefile
package.json

Removes quite a few dependencies

[RFR] Use Karma directly (not through grunt)

---

doc/Dashboard.md
src/javascripts/ng-admin/Main/view/dashboard.html

[RFR] Fix Dashboard bug

---

src/javascripts/ng-admin/Crud/field/maEmbeddedListField.js

[RFR] Fix non editable fields in embedded lists

---

src/sass/ng-admin.scss

[RFR] Fix display of boolean field in embedded_list

---

Makefile
examples/blog/build/fakerest.js
webpack.config.js

[RFR] Fix build on Windows

---

src/javascripts/ng-admin/Crud/field/maChoicesField.js

[RFR] Fix select multiple fails to add choice when removing value

---

src/javascripts/ng-admin/Crud/fieldView/ReferenceManyFieldView.js

[RFR] Allow reference_many field to be used as filter

---

src/sass/ng-admin.scss

[RFR] Fix embedded_list remove button not clickable

---

src/javascripts/ng-admin/Crud/fieldView/ReferenceManyFieldView.js

[RFR] Fix wrong closing tag in reference_many filter

---

package.json

[RFR] Update restangular to version 1.5.2

---

src/sass/ng-admin.scss

[RFR] Move "Remove" button for embedded lists out of the way

---

package.json

[RFR] Update node-sass version dependency to avoid install error

---

src/javascripts/ng-admin/Crud/button/maExportToCsvButton.js

[RFR] Fix export sort field

---

src/javascripts/ng-admin/Crud/field/maReferenceField.js

[RFR] Fix current choice does not appear in autocomplete reference field

---

src/javascripts/ng-admin/Crud/CrudModule.js
src/javascripts/ng-admin/Crud/button/maSubmitButton.js
src/javascripts/ng-admin/Crud/form/create.html
src/javascripts/ng-admin/Crud/form/edit.html

Allows to override the submit button text on the entire application by way of `$provide.decorator()`.

[RFR] Add submit button directive

---

src/javascripts/ng-admin/Crud/field/maDateField.js

[RFR] Fix null default value for DateField

---

doc/Translation.md
src/javascripts/ng-admin/Crud/column/maStringColumn.js
src/javascripts/ng-admin/Crud/delete/batchDelete.html
src/javascripts/ng-admin/Crud/delete/delete.html
src/javascripts/ng-admin/Crud/field/maButtonField.js
src/javascripts/ng-admin/Crud/field/maChoiceField.js
src/javascripts/ng-admin/Crud/field/maChoicesField.js
src/javascripts/ng-admin/Crud/field/maField.js
src/javascripts/ng-admin/Crud/filter/maFilterForm.js
src/javascripts/ng-admin/Crud/form/create.html
src/javascripts/ng-admin/Crud/form/edit.html
src/javascripts/ng-admin/Crud/list/listLayout.html
src/javascripts/ng-admin/Crud/list/maDatagrid.js
src/javascripts/ng-admin/Crud/show/maShowItem.js
src/javascripts/ng-admin/Crud/show/show.html
src/javascripts/ng-admin/Main/component/directive/maDashboardPanel.js
src/javascripts/ng-admin/Main/view/menuBar.html
src/javascripts/test/unit/Crud/field/maFieldSpec.js
src/javascripts/test/unit/Crud/list/maDatagridSpec.js
src/javascripts/test/unit/Main/component/directive/maDashboardPanelSpec.js
src/javascripts/test/unit/Main/component/directive/maMenuBarSpec.js

Entities labels, fields labels, menus labels, choices values are now translatable.

[RFR] Make custom elements translatable

---

UPGRADE-0.7.md

[FIX] wording typo (Typo in Documentation #1078)

---

doc/reference/Entity.md
doc/reference/View.md

Fix for #1041
Requires https://github.com/marmelab/admin-config/pull/66 -- I haven't updated the `admin-config` version or rebuild the "`build/`" files in this PR, as per the contrib guidelines.

#1041 fix encoding of entity ids in REST URLs

---

src/javascripts/ng-admin/Crud/column/maEmbeddedListColumn.js
src/javascripts/ng-admin/Crud/column/maReferencedListColumn.js
src/javascripts/ng-admin/Crud/list/list.html
src/javascripts/ng-admin/Crud/list/maDatagrid.js
src/javascripts/ng-admin/Crud/list/maDatagridController.js
src/javascripts/test/unit/Crud/list/DatagridControllerSpec.js

[RFR] Show sort column in datagrid even with default sort

---

src/javascripts/ng-admin/Crud/field/maChoiceField.js

As specified in #1213, ReferenceField are no longer populated.
This PR aims to fix the issue.
Fix #1213

[RFR] Fix ReferenceField two-step population

---

ISSUE_TEMPLATE.md

work with ng admin > 1.0.0-alpha7
Fix  https://github.com/marmelab/ng-admin/issues/1220

Update issue template with proper plunker

---

src/javascripts/ng-admin/Crud/list/ListLayoutController.js
src/javascripts/test/unit/Crud/list/ListLayoutControllerSpec.js

[RFR] load default value of pinned filter

---

doc/Installation.md

[RFR] Update some docs in regard or ui-view BC break

---

doc/API-mapping.md

- Changed filter to _filters to be more consistent with current version of ng-admin

Edit Api-mapping nested relationships documentation.

---

src/javascripts/ng-admin/Crud/column/maJsonColumn.js
src/javascripts/ng-admin/Crud/delete/batchDelete.html
src/javascripts/ng-admin/Crud/delete/delete.html
src/javascripts/ng-admin/Crud/form/create.html
src/javascripts/ng-admin/Crud/show/show.html
src/javascripts/ng-admin/Main/view/404.html

Rebase of #1147 for milestone 1.0.
Fixes #1146.

[RFR] Remove instances of {0xC2, 0xA0} in source files

---

doc/API-mapping.md
doc/reference/Field.md
package.json
src/javascripts/ng-admin/Crud/list/maDatagrid.js

[RFR] Allow to disable sort on columns

---

Makefile

[RFR] Leave SASS files in lib/sass/ [BC-BREAK]

---

doc/Getting-started.md
doc/reference/View.md

Rebase and replace https://github.com/marmelab/ng-admin/pull/1224

Correct the definition of add full request interceptor

---

src/javascripts/ng-admin/Crud/field/maDateField.js
src/javascripts/test/unit/Crud/field/maDateFieldSpec.js

Fixes #899 and closes #1072 by super-seeding.

[RFR] Allow to update maDateField dynamically

---

src/javascripts/ng-admin/Crud/button/maExportToCsvButton.js

Fix #1116 
To be test with Browserstack.

[RFR] Allow IE11 & Edge to export CSV

---

.npmignore

Fix #1294 
<details>
<summary>Before change, here is the `lib` folder tree</summary>
```bash
lib
├── javascripts
│   ├── ng-admin
│   │   ├── Crud
│   │   │   ├── button
│   │   │   │   ├── maBackButton.js
│   │   │   │   ├── maBackButton.js.map
│   │   │   │   ├── maBatchDeleteButton.js
│   │   │   │   ├── maBatchDeleteButton.js.map
│   │   │   │   ├── maCreateButton.js
│   │   │   │   ├── maCreateButton.js.map
│   │   │   │   ├── maDeleteButton.js
│   │   │   │   ├── maDeleteButton.js.map
│   │   │   │   ├── maEditButton.js
│   │   │   │   ├── maEditButton.js.map
│   │   │   │   ├── maExportToCsvButton.js
│   │   │   │   ├── maExportToCsvButton.js.map
│   │   │   │   ├── maFilterButton.js
│   │   │   │   ├── maFilterButton.js.map
│   │   │   │   ├── maFilteredListButton.js
│   │   │   …
```

[RFR] Remove test files from build

---

doc/reference/Field.md

I've copy pasted and got my code faulty

Fixed misleading typo

---

doc/reference/View.md

[RFR] Improve list view actions documentation

---

src/javascripts/ng-admin/Crud/list/ListLayoutController.js
src/javascripts/test/unit/Crud/list/ListLayoutControllerSpec.js

Related to:
https://github.com/marmelab/ng-admin/pull/1378
https://github.com/marmelab/admin-config/pull/78

[RFR] Do not force defaultValue on filter
